# Generated by Django 2.2.7 on 2019-11-17 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, verbose_name='date of request')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='date of supply starting')),
                ('finish', models.DateField(verbose_name='date of supply finishing')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.CharField(choices=[('SHOP', 'Available in shop'), ('WARE', 'Available in warehouse'), ('REQ', 'Available by request'), ('NOT', 'Not available')], default='NOT', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=2000),
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_shop.Request')),
                ('status', models.BooleanField(default=False, verbose_name='status of delivery request')),
            ],
            bases=('book_shop.request',),
        ),
        migrations.CreateModel(
            name='SupplyBook',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_shop.Book')),
                ('supply', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_shop.Supply')),
            ],
            bases=('book_shop.book',),
        ),
        migrations.AddField(
            model_name='request',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_shop.Book'),
        ),
        migrations.AddField(
            model_name='request',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_shop.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_shop.Publisher'),
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_shop.Request')),
                ('status', models.BooleanField(default=False, verbose_name='status of supply request')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book_shop.Client')),
            ],
            bases=('book_shop.request',),
        ),
    ]
